#
# This file controls the details on the published HTML page.
#
# All the values here are optional, but it will obviously look a lot
# better if you fill them in.
#
# Remove the # from the front of each line, and then edit appropriately.
#

title: Kyle Niemeyer's CV
#abstract:

# This controls which file is shown on the right-hand side of the published
# HTML page.  By default it will take the first PDF or HTML file that it
# finds.  If that doesn't work for you, you can specify the correct file here.
iframe_src: KE_Niemeyer_CV.pdf

# You can specify multiple authors, just follow the pattern below.
# These fields can contain HTML tags.  You probably want to put <br />
# in the address somewhere, indicating a line break.

authors:
- name: Kyle E. Niemeyer
  address: School of Mechanical, Industrial, and Manufacturing Engineering,<br />Oregon State University,<br />Corvallis, OR 97331, USA.
github_username: kyleniemeyer
github_repo: cv
